CREATE TABLE BOARD (
  ID int NOT NULL,
  TITLE varchar(200) NOT NULL,
  DESC varchar(4000) NOT NULL,
  PRIMARY KEY (ID)
);

INSERT INTO BOARD(ID, TITLE, DESC) VALUES(1, '제목1', '내용1');
INSERT INTO BOARD(ID, TITLE, DESC) VALUES(2, '제목2', '내용2');
INSERT INTO BOARD(ID, TITLE, DESC) VALUES(3, '제목3', '내용3');