CREATE SEQUENCE BOARD_SEQ;

CREATE TABLE BOARD (
  ID int NOT NULL,
  TITLE varchar(200) NOT NULL,
  DESC varchar(4000) NOT NULL,
  CREATE_DT TIMESTAMP,
  PRIMARY KEY (ID)
);

INSERT INTO BOARD(ID, TITLE, DESC, CREATE_DT) VALUES(BOARD_SEQ.NEXTVAL, '제목1', '내용1', CURRENT_TIMESTAMP());
INSERT INTO BOARD(ID, TITLE, DESC, CREATE_DT) VALUES(BOARD_SEQ.NEXTVAL, '제목2', '내용2', CURRENT_TIMESTAMP());
INSERT INTO BOARD(ID, TITLE, DESC, CREATE_DT) VALUES(BOARD_SEQ.NEXTVAL, '제목3', '내용3', CURRENT_TIMESTAMP());